services:
  app:
    build: .
    container_name: app
    command: uvicorn app.index:app --host 0.0.0.0 --port 9000 --reload
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@my_db:5432/postgres
    restart: always
    depends_on:
      my_db:
        condition: service_healthy

  migrate:
    build: .
    container_name: migrate
    command: alembic upgrade head
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@my_db:5432/postgres
    depends_on:
      my_db:
        condition: service_healthy

  my_db:
    image: postgres:16
    container_name: my_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
