"""add subtitle model to env

Revision ID: 03cb370fa158
Revises: 25e6efebca6a
Create Date: 2025-10-11 13:12:58.484393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03cb370fa158'
down_revision: Union[str, Sequence[str], None] = '25e6efebca6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtitles',
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtitles')
    # ### end Alembic commands ###
