"""add server default to updated_at

Revision ID: 16c20d071e2d
Revises: a5918a7553a7
Create Date: 2025-10-08 10:05:33.914346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c20d071e2d'
down_revision: Union[str, Sequence[str], None] = 'a5918a7553a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'description')
    op.drop_column('videos', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
