"""restructure user and social_account models

Revision ID: 51369595308d
Revises: 5fee438d3493
Create Date: 2025-10-04 12:47:24.628082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51369595308d'
down_revision: Union[str, Sequence[str], None] = '5fee438d3493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('provider', postgresql.ENUM('GOOGLE', 'DISCORD', 'GITHUB', 'X', name='providers_enum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
