"""auto

Revision ID: b3801678cf68
Revises: 290d9202186c
Create Date: 2025-10-13 11:10:27.160655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3801678cf68'
down_revision: Union[str, Sequence[str], None] = '290d9202186c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'title')
    op.drop_column('videos', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('title', sa.VARCHAR(length=70), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
