"""auto

Revision ID: b565b0cb1df6
Revises: 94a04aa37211
Create Date: 2025-10-21 09:34:55.052569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b565b0cb1df6'
down_revision: Union[str, Sequence[str], None] = '94a04aa37211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'logs', ['video_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='unique')
    # ### end Alembic commands ###
