"""auto

Revision ID: bec8e535fa01
Revises: b565b0cb1df6
Create Date: 2025-10-21 13:52:34.905324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec8e535fa01'
down_revision: Union[str, Sequence[str], None] = 'b565b0cb1df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('logs_video_id_key'), 'logs', type_='unique')
    op.create_index(op.f('ix_logs_thread_id'), 'logs', ['thread_id'], unique=False)
    op.create_index(op.f('ix_logs_user_id'), 'logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_logs_video_id'), 'logs', ['video_id'], unique=True)
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_subtitles_video_id'), 'subtitles', ['video_id'], unique=False)
    op.create_index(op.f('ix_threads_user_id'), 'threads', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_bios_user_id'), 'user_bios', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_localizations_video_id'), 'video_localizations', ['video_id'], unique=False)
    op.create_index(op.f('ix_videos_user_id'), 'videos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_user_id'), table_name='videos')
    op.drop_index(op.f('ix_video_localizations_video_id'), table_name='video_localizations')
    op.drop_index(op.f('ix_user_bios_user_id'), table_name='user_bios')
    op.drop_index(op.f('ix_threads_user_id'), table_name='threads')
    op.drop_index(op.f('ix_subtitles_video_id'), table_name='subtitles')
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_logs_video_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_user_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_thread_id'), table_name='logs')
    op.create_unique_constraint(op.f('logs_video_id_key'), 'logs', ['video_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
